name: Build Full Stack Application

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  backend-build:
    name: Build Spring Boot Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build Backend
        run: mvn clean install

  frontend-build:
    name: Build React Frontend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ui

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Frontend Dependencies
        run: npm install

      - name: Build Frontend
        run: npm run build

    backend-docker-build:
      name: Build Backend Docker Image
      runs-on: ubuntu-latest

      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Build Backend Docker Image
          run: docker build -t product-service-backend .

    frontend-docker-build:
      name: Build Frontend Docker Image
      runs-on: ubuntu-latest

      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Build Frontend Docker Image
          run: docker build -t product-service-frontend ./ui